### ISSUE TITLE
Should we display Sell-to EU price OR buy-From EU price?

### ISSUE THREAD

**Issue by MikeJeffers** [MikeJeffers/freecol-contrib#15]
Currently showing buy prices.
But from Mike Pope's email:

> > We've encountered just the trade windows with the natives so far,
> 
> That would be the main one where a player may reasonably be wondering
> whether it is better to _sell some goods_ in Europe.

From a player's perspective, are they wondering if selling to natives vs EU is better?  Or when they are buying from natives, are they wondering if it is cheaper to buy from EU?  Should we show both?  
DISCUSS

**Comment by dongkatsu** [comment]
Resolved.
