### ISSUE TITLE
Gold trade display disappears in conjunction with demand and offer

### ISSUE THREAD

**Issue by dongkatsu** [MikeJeffers/freecol-contrib#24]
Gold trade display disappears if the other player's gold is added to the trade.
I.e. if player adds 50 gold, it displays 50 gold as offer. But if subsequently, gold is demanded from other player, the previous 50 gold displayed disappears and only the gold demanded from other player displays.

Something seems to be resetting every time gold is added from opposite player...not quite sure what it is

**Comment by MikeJeffers** [comment]
I think this is working as intended.  Let's verify @ meeting today based on clean branch.

**Comment by MikeJeffers** [comment]
Working as intended
