### ISSUE TITLE
TEST- GUI pricing

### ISSUE THREAD

**Issue by MikeJeffers** [MikeJeffers/freecol-contrib#8]
Does price display, is price correct in display
Test for digit overflows
Units accurate?
Legible?

**Comment by MikeJeffers** [comment]
TEST CASES:
-TRADE NEGOTIATION WITH EU COLONY
-DIPLOMATIC NEGOTIATION WITH EU COLONY
-MISC NEGOTIATION WITH EU COLONY
-TRADE WITH NATIVES

**Comment by MikeJeffers** [comment]
Are all testing for 43 done?

**Comment by louisez221** [comment]
Done. I don't think looting is affected. Docs up too.
